### ISSUE TITLE
Route Version C of PCB

### ISSUE THREAD

**Issue by misprit7** [UBC-Rocket/WB-AV-4500-FC#11]
As the name indicates, the rev c version of the pcb still needs to be routed. I wasn't able to keep much of the original routing so this will actually be quite a bit of it.

**Comment by Esouder** [comment]
@misprit7 Can we consider this done, or should it wait until the PCB is completely ready to order? On the one hand the main rerouting is done, but it's not totally done-done.

**Comment by misprit7** [comment]
Yeah we can call this done. It still needs a final look over but that's for everything not just routing.
