### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by Esouder** [UBC-Rocket/WB-AV-4500-FC#4]
This repo has just under a gig of 'history' that's being stored for some ungodly reason. Would like to fix this.

**Comment by Esouder** [comment]
For the time being at least, we've elected to leave this be; it's not critically important

**Comment by misprit7** [comment]
Just looked into this a bit more, and the second answer in [this stackoverflow post](https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history) seemed to do the trick. I reduced the size of the DAQ board repo and I'll do this one next (just waiting for it to download).

**Comment by misprit7** [comment]
Seemed to work with this repository as well, I'm going to call this fixed.

**Comment by Esouder** [comment]
Yay, but also damn that was the exact same answer I tried to follow the
first time...

**Comment by misprit7** [comment]
That's weird, it was relatively fast (a few seconds) for and I didn't have any problems.

**Comment by Esouder** [comment]
Ah, actually looking at it more I think I may have used `--tree-filter` not `--index-filter`
